version: "3.9"

services:
  mcp-doc-retriever:
    container_name: mcp-doc-retriever
    build: .
    ports:
      - "5000:5000"
    environment:
      ARANGO_HOST: http://arangodb:8529
      ARANGO_USER: root
      ARANGO_PASSWORD: ${ARANGO_PASSWORD:-mcp_password}
    volumes:
      - download_data:/app/downloads
      - uploads:/app/uploads
      - output:/app/output
      - corrections:/app/corrections
    depends_on:
      - arangodb
      - redis
      - labelstudio
    restart: unless-stopped

  labelstudio:
    image: heartexlabs/label-studio:latest
    container_name: labelstudio
    ports:
      - "8080:8080"
    environment:
      LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED: true
      LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT: /label-studio/data
    volumes:
      - uploads:/label-studio/data/uploads
      - output:/label-studio/data/output
      - corrections:/label-studio/data/corrections
    depends_on:
      - redis

  arangodb:
    container_name: mcp-arangodb
    image: arangodb:latest
    ports:
      - "8529:8529"
    environment:
      ARANGO_ROOT_PASSWORD: ${ARANGO_PASSWORD:-mcp_password}
    volumes:
      - arango_data:/var/lib/arangodb3

  redis:
    container_name: mcp-redis
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  download_data:
  uploads:
  output:
  corrections:
  arango_data:
  redis_data: